### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by projkov** [beda-software/fhir-faker#1]
- [ ] Prepare library structure
- [ ] [Create base fakers for general purpose data types](https://www.hl7.org/fhir/datatypes.html) 
  - [ ] HumanName
  - [ ] ContactPoint
  - [ ] Address
  - [ ] Identifier
  - [ ] Coding
  - [ ] CodableConcept
- [ ] Use https://github.com/beda-software/aidbox-ts-generator/tree/master to generate fakers for FHIR resources
  - [ ] Organization
  - [ ] Patient
  - [ ] Practitioner
  - [ ] Location
  - [ ] PractitionerRole
  - [ ] Appointment
  - [ ] Encounter
  - [ ] EpisodeOfCare
  - [ ] Condition
  - [ ] Observation

**Comment by ir4y** [comment]
1. Add initialization parameter format `aidbox` | `fhir`.    
2. Faker always returns a single resource or bundle with resource and all dependencies.
